global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # - job_name: "cadvisor"
  #   static_configs:
  #     - targets: ["cadvisor:8098"]
  # - job_name: "tempo"
  #   static_configs:
  #     - targets: ["tempo:3200"]
  # - job_name: "rust-observability"
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ["127.0.0.1:3000"]
  # - job_name: "vector"
  #   static_configs:
  #     - targets: ["vector:9598"]
